### ISSUE TITLE
Dependency Issues with GavUI

### ISSUE THREAD

**Issue by 7777777lai** [GT3CH1/minecraft-mod#41]
**Describe the bug**
Cannot launch the game due to a dependency issue with gavui

**To Reproduce**

1. Download gavinsmod version 1.3.1
2. Launch the game
3. Get an error message, listed below.

**Expected behavior**
The mod should work without having to install gavui

**Screenshots/Video**

**Version Info (please complete the following information):**

- OS: ?
- Mod Version: 1.3.1

**Additional context**
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install gavui, any version.
Unmet dependency listing:
	 - Mod 'GavinsMod' (gavinsmod) 1.3.1 requires any version of gavui, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by GT3CH1** [comment]
Thanks! I'll be looking into this. It's odd since gavui should've been
bundled in already.

**Comment by GT3CH1** [comment]
This error has been fixed, and has been released under `v1.3.1 hotfix 1`.
You may obtain a download for Minecraft 1.19.1 or 1.19.2 at this link.
[https://github.com/GT3CH1/minecraft-mod/releases/tag/v1.3.1-hotfix1](https://github.com/GT3CH1/minecraft-mod/releases/tag/v1.3.1-hotfix1)
