### ISSUE TITLE
This is a minecraft hacked client not a mod

### ISSUE THREAD

**Issue by AlexanderMaxRanabel** [GT3CH1/minecraft-mod#49]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ajrichins** [comment]
hacked clients are mods

**Comment by GT3CH1** [comment]
as @ajrichins said, hacked clients are technically speaking, _mods_, although I would argue that they are in their own category (such as clients). I've debated whether or not adding something that states this, but I've currently elected not to as the current state of my mod lacks a lot of features when compared to other clients - for example, profile switching. Adding such features that would turn this mod into more of a client are currently not on the list of things I want to do with it. 

For future reference, please fill out the issue template to the best of your ability. Doing so will allow for more accurate responses from the community and myself.
