### ISSUE TITLE
1.4.1+1.19.4 crashes on load

### ISSUE THREAD

**Issue by raydeejay** [GT3CH1/minecraft-mod#51]
**Describe the bug**
The game crashes trying to use shouldDrawSide which for some reason doesn't exist.

**To Reproduce**
1. Add the .jar to mods/
2. Launch the game
3. Game exits with -1

**Expected behavior**
The game starts instead of crashing

**Version Info (please complete the following information):**
Linux, mc-installer snap

**Additional context**
Attached log
[latest.log](https://github.com/GT3CH1/minecraft-mod/files/11003051/latest.log)

**Comment by GT3CH1** [comment]
Interesting - thanks for filling out a report. I will look into this shortly. I have no idea why it would crash, as when I tested it it did not. Thanks again!

**Comment by GT3CH1** [comment]
I have found the problem - I had thought that I can write Mixin's using Kotlin. That is currently not the case, as you have to use Java at the present moment. I will need to rewrite the mixins back into java (shouldn't take too long) and then update the release with a working version.

**Comment by GT3CH1** [comment]
I have fixed the bug and will be closing this issue as PR #52 was merged in. Please download the fixed version on the [release page](https://github.com/GT3CH1/minecraft-mod/releases/tag/v1.4.1-hotfix1). 

If you run into any other bugs, or would like to have a feature added - please open up another issue. Thanks!
