### ISSUE TITLE
Sporadic crashes with NoFall enabled

### ISSUE THREAD

**Issue by raydeejay** [GT3CH1/minecraft-mod#59]
**Describe the bug**
From time to time, the game will crash trying to access an implementation of com.peasenet.mixinterface.IClientPlayerEntity.getVelocity()

**To Reproduce**
Enable NoFall. I've triggered this bug twice, once by flying around with Fly and NoFall and accidentally disabling fly and falling on something. The second time was flying with elytra, only NoFall enabled, to the top of an obsidian pillar in the end.

**Expected behavior**
The game doesn't crash :-)

**Version Info (please complete the following information):**
1.4.1-hotfix1+1.19.4
[crash-2023-03-25_18.32.56-client.txt](https://github.com/GT3CH1/minecraft-mod/files/11069796/crash-2023-03-25_18.32.56-client.txt)

**Comment by GT3CH1** [comment]
Yikes, that's an uh-oh on my behalf. I'll work on this.

**Comment by GT3CH1** [comment]
I was finally able to get to this today - I have patched and merged this into the mainline branch, with a release available as 1.4.2. As always, please let me know if you find something else funky in the mod. Thanks again!
