### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'gavinsmod'!

### ISSUE THREAD

**Issue by DarkHoden** [GT3CH1/minecraft-mod#64]
**Describe the bug**
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'gavinsmod'!

**To Reproduce**

1. Go to 'Download Mod and put in the .minecraft\mods'
2. Click on 'Start Minecraft'
3. Scroll down to 'None'

**Expected behavior**
That it works

**Screenshots/Video**
![grafik](https://user-images.githubusercontent.com/129884854/229860514-121ad8f2-d63f-47d6-9c0d-a35d8f2ea8dc.png)

**Version Info (please complete the following information):**

- OS: Windows 11
- Mod Version: 1.4.2 for Minecraft 1.19.4

**Additional context**
Here is the File:
[crash-2023-04-04_18.33.25-client.txt](https://github.com/GT3CH1/minecraft-mod/files/11150898/crash-2023-04-04_18.33.25-client.txt)
If this don't work here is the Link: https://anonfiles.com/c8j8W6iezd/crash_2023_04_04_18_33_25_client_txt

**Comment by GT3CH1** [comment]
Hi, 
Thank you for filling this out. I forgot to update the readme to include a step in the installation instructions to have users install the `Fabric Language Kotlin` mod. I have update the readme to reflect this. Please install the `Fabric Language Kotlin` for MC 1.19.3 and kotlin 1.8.20 (here)[https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin/files].

I was able to reproduce this issue and was able to fix it by deleting that mod, running minecraft (crashed). I reinstalled the language adapter and minecraft worked.

Please let me know if you have any further issues by responding here. Thanks.

**Comment by DarkHoden** [comment]
For 1.19.3 ... i Play on 1.19.4

**Comment by DarkHoden** [comment]
Both in the Mod Folder ?. Or Kotlin 1.8.20 seperate (Install)

**Comment by GT3CH1** [comment]
It should work the same.

**Comment by DarkHoden** [comment]
And 
![grafik](https://user-images.githubusercontent.com/129884854/229869795-406c53e8-a7bc-415f-ba27-7c9ca5194801.png)
or 
![grafik](https://user-images.githubusercontent.com/129884854/229869847-57d0c8ac-f739-4148-b5c7-40e75d0b19d1.png)

**Comment by GT3CH1** [comment]
Use the link I attached in the previous comment or the link that I have
updated in the readme of the mod. You are currently trying to install the
compiler for the language which is not required.

**Comment by DarkHoden** [comment]
The Link only goes to the 
![grafik](https://user-images.githubusercontent.com/129884854/229872297-bdd85144-f0b1-4691-b764-eac497785d7d.png)

**Comment by DarkHoden** [comment]
So i only need this.

**Comment by GT3CH1** [comment]
Yes and click the download button on that page. Drag and drop the
downloaded .jar file to your mods folder.

I did not link directly to the file as that is generally regarded as bad
practice.

**Comment by DarkHoden** [comment]
Good. Just a Question those the XRAY work with Optifine? Or should i unload it.

**Comment by GT3CH1** [comment]
I have not done anything to support optifine and x-ray. I do know that
sodium works with x-ray.

**Comment by DarkHoden** [comment]
Well then i will see it.
