### ISSUE TITLE
Enabling some modules disables View Bobbing

### ISSUE THREAD

**Issue by raydeejay** [GT3CH1/minecraft-mod#65]
**Describe the bug**
Enabling any of the following modules disables View Bobbing. Turning them off doesn't always restore it.

- NoClip (I can see why this one would be acceptable/required)
- AntiHurt
- Waypoints
- Tracers

**To Reproduce**
Enable any of the modules while having View Bobbing enabled in options.

**Version Info (please complete the following information):**

1.4.2

**Comment by GT3CH1** [comment]
Disabling view bobbing when having a mod that uses a tracer (ie, waypoints) is intentional.
However, AntiHurt should only fire when you get hurt, and I can tell by reading the code that is not happening at the moment. I will look into that. Thanks.

**Comment by GT3CH1** [comment]
I have found the bug which you originally reported (there was one tracer mod that did not unsubscribe from the `CameraBob` event.) I am working on fixing this.
