### ISSUE TITLE
The fullbright isn't working.

### ISSUE THREAD

**Issue by CynamicalHTML** [GT3CH1/minecraft-mod#69]
**Describe the bug**
The fullbright turns on and off randomly even if i have no hotkeyes set to it.
When I try to enable it it turns of again.

**To Reproduce**

1. Go to 'Menu'
2. Click on 'Fullbright'
3. See error

**Expected behavior**
I expected for it to just keep Fulbright on.

**Screenshots/Video**
**
![image](https://github.com/GT3CH1/minecraft-mod/assets/111830759/8e6b3a1d-1b0a-4215-8aca-0c63ffb2f536)
**
**Version Info (please complete the following information):**

- OS: [Windows 10]
- Mod Version: [1.4.3]

**Additional context**
Idk how to fix.

**Comment by GT3CH1** [comment]
Is auto fullbright turned on? If so, go to the settings gui ("o" by
default)>render>fullbright and see if it is turned on. If it is, this
behavior is expected. If it is not, then it isn't.

**Comment by GT3CH1** [comment]
@CynamicalHTML were you able to fix this issue?

**Comment by GT3CH1** [comment]
@CynamicalHTML Any luck? I will be closing this issue in 24 hours if I do not hear back.

**Comment by GT3CH1** [comment]
Closing due to no response and unable to replicate the problem above.
